# Generated by Django 5.2.9 on 2026-01-06 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_country_code', models.CharField(choices=[('+40', '🇷🇴 Romania (+40)'), ('+373', '🇲🇩 Moldova (+373)'), ('+380', '🇺🇦 Ukraine (+380)'), ('+1', '🇺🇸 USA/Canada (+1)'), ('+44', '🇬🇧 UK (+44)'), ('+49', '🇩🇪 Germany (+49)'), ('+33', '🇫🇷 France (+33)'), ('+34', '🇪🇸 Spain (+34)'), ('+39', '🇮🇹 Italy (+39)'), ('+43', '🇦🇹 Austria (+43)'), ('+41', '🇨🇭 Switzerland (+41)'), ('+31', '🇳🇱 Netherlands (+31)'), ('+32', '🇧🇪 Belgium (+32)'), ('+48', '🇵🇱 Poland (+48)'), ('+36', '🇭🇺 Hungary (+36)'), ('+420', '🇨🇿 Czech Republic (+420)'), ('+359', '🇧🇬 Bulgaria (+359)'), ('+30', '🇬🇷 Greece (+30)'), ('+90', '🇹🇷 Turkey (+90)'), ('+7', '🇷🇺 Russia (+7)')], default='+40', max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
