# Generated by Django 5.2.9 on 2025-12-03 11:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_discountcode_booking_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='discount_code',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='discount_amount',
            new_name='total_discount',
        ),
        migrations.AddField(
            model_name='booking',
            name='price_breakdown',
            field=models.JSONField(blank=True, default=list, help_text='Detailed price breakdown per day'),
        ),
        migrations.CreateModel(
            name='DiscountPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Winter Sale', 'Early Bird'", max_length=100)),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Percentage discount (1-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_periods', to='app.apartment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='DiscountCode',
        ),
    ]
