# Generated by Django 5.2.9 on 2025-12-07 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_booking_currency'),
    ]

    operations = [
        # Remove discount-related fields from Booking model
        migrations.RemoveField(
            model_name='booking',
            name='total_discount',
        ),
        # Delete DiscountPeriod model
        migrations.DeleteModel(
            name='DiscountPeriod',
        ),
    ]
