# Generated by Django 5.2.9 on 2025-12-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_discount_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='price_per_guest',
            field=models.JSONField(blank=True, default=dict, help_text='Price per guest count: {1: 100, 2: 150, 3: 200, etc.}'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='pricing_type',
            field=models.CharField(choices=[('APARTMENT', 'Per Apartment'), ('GUEST', 'Per Guest')], default='APARTMENT', help_text='Pricing model: per apartment or per guest', max_length=20),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='base_price_per_night',
            field=models.DecimalField(decimal_places=2, help_text='Base price per night (for apartment) or price for 1 guest', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='rule_type',
            field=models.CharField(choices=[('SEASONAL', 'Seasonal'), ('WEEKEND', 'Weekend'), ('HOLIDAY', 'Holiday')], max_length=20),
        ),
    ]
