# Generated by Django 5.2.9 on 2025-12-09 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_apartment_price_per_guest_apartment_pricing_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='external_uid',
            field=models.CharField(blank=True, help_text='UID from external iCal event', max_length=255),
        ),
        migrations.AddField(
            model_name='availability',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('ICAL', 'iCal Import')], default='MANUAL', max_length=20),
        ),
        migrations.CreateModel(
            name='ICalFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Airbnb, Booking.com', max_length=100)),
                ('url', models.URLField(help_text='iCal feed URL', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, max_length=50)),
                ('sync_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ical_feeds', to='app.apartment')),
            ],
            options={
                'verbose_name': 'iCal Feed',
                'verbose_name_plural': 'iCal Feeds',
                'ordering': ['name'],
            },
        ),
    ]
