# Generated by Django 5.2.9 on 2025-12-09 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_ical_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='ical_feed',
            field=models.ForeignKey(blank=True, help_text='The iCal feed this block came from', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='app.icalfeed'),
        ),
    ]
