# Generated by Django 5.2.9 on 2026-01-07 10:02

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_availability_ical_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='icalfeed',
            name='circuit_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='icalfeed',
            name='consecutive_failures',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='icalfeed',
            name='is_circuit_open',
            field=models.BooleanField(default=False, help_text='If true, sync is paused'),
        ),
        migrations.AddField(
            model_name='icalfeed',
            name='last_content_hash',
            field=models.CharField(blank=True, help_text='SHA256 of last content', max_length=64),
        ),
        migrations.AddField(
            model_name='icalfeed',
            name='last_etag',
            field=models.CharField(blank=True, help_text='ETag from last response', max_length=255),
        ),
        migrations.AddField(
            model_name='icalfeed',
            name='last_events_created',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='icalfeed',
            name='last_events_parsed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='icalfeed',
            name='last_events_removed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='icalfeed',
            name='last_events_updated',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='icalfeed',
            name='last_fetch_bytes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='icalfeed',
            name='last_modified_header',
            field=models.CharField(blank=True, help_text='Last-Modified header', max_length=100),
        ),
        migrations.AddField(
            model_name='icalfeed',
            name='last_sync_duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='icalfeed',
            name='next_sync_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='icalfeed',
            name='priority',
            field=models.PositiveIntegerField(default=5, help_text='1=highest, 10=lowest'),
        ),
        migrations.AddField(
            model_name='icalfeed',
            name='successful_syncs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='icalfeed',
            name='sync_interval_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Minutes between syncs'),
        ),
        migrations.AddField(
            model_name='icalfeed',
            name='total_syncs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apartmentimage',
            name='image',
            field=models.ImageField(upload_to=app.models.apartment_image_path),
        ),
        migrations.CreateModel(
            name='ICalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(help_text='VEVENT UID', max_length=500)),
                ('recurrence_id', models.CharField(blank=True, help_text='For recurring event instances', max_length=100)),
                ('dtstart', models.DateField(help_text='Event start date')),
                ('dtend', models.DateField(help_text='Event end date (exclusive)')),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(default='CONFIRMED', help_text='CONFIRMED/TENTATIVE/CANCELLED', max_length=50)),
                ('sequence', models.PositiveIntegerField(default=0, help_text='iCal SEQUENCE')),
                ('dtstamp', models.DateTimeField(blank=True, help_text='iCal DTSTAMP', null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('missing_since', models.DateTimeField(blank=True, help_text='When event stopped appearing in feed', null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('raw_vevent', models.TextField(blank=True, help_text='Original VEVENT content')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='app.icalfeed')),
            ],
            options={
                'verbose_name': 'iCal Event',
                'verbose_name_plural': 'iCal Events',
                'ordering': ['dtstart'],
            },
        ),
        migrations.AddField(
            model_name='availability',
            name='ical_event',
            field=models.ForeignKey(blank=True, help_text='The specific iCal event this block came from', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='app.icalevent'),
        ),
        migrations.AddIndex(
            model_name='icalevent',
            index=models.Index(fields=['feed', 'dtstart'], name='app_icaleve_feed_id_79761a_idx'),
        ),
        migrations.AddIndex(
            model_name='icalevent',
            index=models.Index(fields=['missing_since'], name='app_icaleve_missing_0e61c9_idx'),
        ),
        migrations.AddConstraint(
            model_name='icalevent',
            constraint=models.UniqueConstraint(fields=('feed', 'uid', 'recurrence_id'), name='unique_ical_event_per_feed'),
        ),
    ]
